// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52udHX7J_7d7TPKnz-UDwrYZcoEJZVKA',
    appId: '1:860807262932:web:475a8204e8d19c31bbc141',
    messagingSenderId: '860807262932',
    projectId: 'citroon-1bce2',
    authDomain: 'citroon-1bce2.firebaseapp.com',
    storageBucket: 'citroon-1bce2.appspot.com',
    measurementId: 'G-QMEW13D29E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNqljKizrVxle5nTiqtLo1-as9JxeDwo',
    appId: '1:860807262932:android:8a03c8a1afec527cbbc141',
    messagingSenderId: '860807262932',
    projectId: 'citroon-1bce2',
    storageBucket: 'citroon-1bce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57Cn57DxdrBJQwXYcHTOuu07qPXctKmw',
    appId: '1:860807262932:ios:156cdad7676dc1b5bbc141',
    messagingSenderId: '860807262932',
    projectId: 'citroon-1bce2',
    storageBucket: 'citroon-1bce2.appspot.com',
    iosClientId: '860807262932-qujueh0ercrsg2d57nsk1g0tedho10vo.apps.googleusercontent.com',
    iosBundleId: 'org.vaadd.citroon',
  );
}
